### PR TITLE
upgrade to RN0.42RC3

### PR DESCRIPTION
**Pull request by nihgwu**

### CODE REVIEW

**Comment by SamSaffron** [comment]
Cool, will confirm this all works shortly 👍  

Can you email me at sam.saffron<at>gmail.com so I can sort out paypal

**Comment by SamSaffron** [comment]
seem to be getting: 

```In file included from /Users/sam/Source/DiscourseMobile/node_modules/react-native/Libraries/ActionSheetIOS/RCTActionSheetManager.m:10:
/Users/sam/Source/DiscourseMobile/node_modules/react-native/Libraries/ActionSheetIOS/RCTActionSheetManager.h:12:9: fatal error: 'React/RCTBridge.h' file not found
#import <React/RCTBridge.h>
        ^


** BUILD FAILED **


The following commands produced analyzer issues:
	Analyze RCTActionSheetManager.m
(1 command with analyzer issues)


The following build commands failed:
	CompileC /Users/sam/Source/DiscourseMobile/ios/build/Build/Intermediates/RCTSettings.build/Debug-iphonesimulator/RCTSettings.build/Objects-normal/x86_64/RCTSettingsManager.o RCTSettingsManager.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)

```

When I run 

```
react-native run-ios
```

**Comment by SamSaffron** [comment]
also totally failed when I try to compile in xcode :(

**Comment by nihgwu** [comment]
See the same errors when I download from zipped file, I'll try to figure out why, sorry for delay

**Comment by nihgwu** [comment]
Here is a trick, delete all the `Libraries` except `React`, build, then discard the change, now you can build successfully, but I still can't build from cli.

**Comment by nihgwu** [comment]
I need to sleep now, I think I've found the solution, will send a patch tomorrow, I'm from China 😄

**Comment by SamSaffron** [comment]
Thanks Neo  !!!

**Comment by nihgwu** [comment]
Hopefully I don't drop any configs

1. Why your target is 9.0+
2. Orientation is supported by RN itself now, no need a 3rd-party library any more
3. use `useNativeDriver` everywhere when available, will make Animation much more smooth

**Comment by SamSaffron** [comment]
thanks, will merge soon, ping me via email!

**Comment by nihgwu** [comment]
can you build now? I'll wait until this be merged 😄

**Comment by SamSaffron** [comment]
Seems to be working find now :heart: thanks so much

> Why your target is 9.0+

I really did not want to support anything earlier, is there something else you would recommend here? 

> Orientation is supported by RN itself now, no need a 3rd-party library any more 

Would love a PR to remove this dependency! 

> use useNativeDriver everywhere when available, will make Animation much more smooth

Would also love a PR for this.

**Comment by jjaffeux** [comment]
@nihgwu sorry to bother, do you know where the documentation is explaining `Orientation` please? Couldn't find anything.

**Comment by nihgwu** [comment]
@jjaffeux sorry it's my mistake, only Modal support Orientation

**Comment by jjaffeux** [comment]
@nihgwu ok ;) thanks

**Pull request merged**
