### PR TITLE
DEV: Add additional languages

### PR DESCRIPTION
**Pull request by gschlager**
@pmusaraj I'm not sure about the language codes. Please double check that "pt-BR",  "zh-CN" and "zh-TW" actually works.

### CODE REVIEW

**Review by pmusaraj — COMMENTED** [review]
Sorry for the delay here @gschlager. 

The syntax works, but the JS module resolver doesn't like that the language files are empty, it gives me a compilation error locally when I try with pt-BR, zh-CN or zh-TW.

**Comment by gschlager** [comment]
Huh, weird! :open_mouth: They shouldn't be empty as those languages are fully translated on Crowdin. I'll have a look. Must be a bug somewhere in the translator-bot code or on Crowdin. :thinking:

**Comment by gschlager** [comment]
@pmusaraj Fixed in https://github.com/discourse/DiscourseMobile/pull/169. I rebased this PR. Please give it another try.

**Review by pmusaraj — APPROVED** [review]
Yeah, this now looks great, thanks!

**Pull request merged**
